name: CI
on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}  # unique per branch
  # cancel previous runs on the same branch, except for master
  cancel-in-progress: ${{ github.ref != 'master' }}
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  QEMUv8_check1:
    name: make check (QEMUv8)
    runs-on: ubuntu-24.04
    container: ghcr.io/${{ vars.CI_IMAGE_OWNER || 'op-tee' }}/optee_os/ci-check-image
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Restore build cache
        uses: actions/cache@v6
        with:
          path: /github/home/.cache/ccache
          key: qemuv8_check-cache-${{ github.sha }}
          restore-keys: |
            qemuv8_check-cache-
      - name: Check
        shell: bash
        run: |
          export LC_ALL=C
          export BR2_CCACHE_DIR=/github/home/.cache/ccache
          export CFG_TEE_CORE_LOG_LEVEL=0
          export DUMP_LOGS_ON_ERROR=1

          CHECKOUT=$PWD
          TOP=/optee_repo_qemu
          cd $TOP
          repo init -u "https://github.com/${{ vars.MANIFEST_OWNER || 'op-tee' }}/manifest.git" -m qemu_v8.xml
          repo sync --force-sync
          rm -rf $TOP/optee_ftpm
          ln -s "${CHECKOUT}" ${TOP}/optee_ftpm
          cd ${TOP}/build

          make -j$(nproc) check MEASURED_BOOT_FTPM=y CHECK_TESTS=xtest XTEST_ARGS=regression_1041
